### ISSUE TITLE
Can I specify presets without having to place all JavaScript inside a string?

### ISSUE THREAD

**Issue by steve-taylor** [Daniel15/babel-standalone#45] opened 2016-08-04 13:27 UTC
According to README.md, if I want to specify plugins (e.g. `react`), I have to do something like this:

```javascript
var input = 'const getMessage = () => "Hello World";';
var output = Babel.transform(input, { presets: ['es2015'] }).code;
```

In other words, all the JavaScript code to be transformed has to come from a string instead of a `<script type="text/babel"></script>` element. Is this right? If not, is there a complete example of an html page in which presets are specified?

**Comment by Daniel15** [comment] 2016-08-05 22:44
Not possible at the moment - Duplicate of #33

**Closed by Daniel15** 2016-08-05 22:44 UTC
