### ISSUE TITLE
sourceMaps

### ISSUE THREAD

**Issue by matthewp** [Daniel15/babel-standalone#10] opened 2016-01-21 14:24 UTC
First, thanks a lot for this project, it's been very useful.

I'm actually considering using babel-standalone within Node because babel 6 is prohibitively slow in NPM 2.x.  The one problem I've encountered is that sourceMaps don't seem to work with babel-standalone. I can look into why, but was just wondering if you knew anything about this.

**Comment by antivanov** [comment] 2016-01-26 12:07
I am having the same problem, trying to figure out the reason. I see that `//# sourceMappingURL=` is included into the transpiled file at the bottom, but the browser (Chrome) does not show the sources. I tried transpiling the same sources with an older Babel version and the sources were visible in the browser. Looks like the problem is either in the newer version of Babel or in `babel-standalone`.

**Comment by antivanov** [comment] 2016-01-26 15:59
In my case the reason seems to be the AMD modules plugin `transform-es2015-modules-amd` as when I am commenting it out the source maps are fully generated and work properly.

```
        presets: ['es2015', 'stage-0', 'stage-1', 'stage-2', 'stage-3', 'react']
        //plugins: ['transform-es2015-modules-amd']
```

I am also trying to debug Babel and find the root cause.

**Comment by matthewp** [comment] 2016-01-26 16:02
Ah, I was using amd as well. That must be it.

**Comment by Daniel15** [comment] 2016-03-14 04:52
I'm going to close this issue since it sounds like it's a core Babel issue (https://phabricator.babeljs.io/T6766) and should be tracked there. Thanks for reporting it!

**Closed by Daniel15** 2016-03-14 04:52 UTC
